name: Default YML File
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
env:
  DAY_OF_WEEK: Monday
jobs: 
  Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      env:
        Greeting: Hello
      steps:
        - name: "Say Hello Mona it's Monday"
          run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
            env:
              First_Name: Mona
